# Generated by Django 2.1.2 on 2018-12-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_remove_person_creatre_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='award',
            name='descript_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='award',
            name='exclude_seniority',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name='person',
            name='award',
        ),
        migrations.AddField(
            model_name='person',
            name='award',
            field=models.ManyToManyField(to='lottery.Award'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
