# Generated by Django 2.1.2 on 2018-12-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_auto_20181209_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='exclude_seniority',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='seniority',
            field=models.IntegerField(default=0),
        ),
    ]
