# Generated by Django 2.1.2 on 2018-12-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_auto_20181209_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='award',
            field=models.ManyToManyField(null=True, to='lottery.Award'),
        ),
    ]
