# Generated by Django 2.1.2 on 2018-12-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_auto_20181209_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='exclude_seniority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
