# Generated by Django 2.1.2 on 2018-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_auto_20181209_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='exclude_seniority',
        ),
        migrations.RemoveField(
            model_name='award',
            name='second_selection',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='award',
            name='award_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='award',
            name='first_selection',
            field=models.IntegerField(default=1),
        ),
    ]
