# Generated by Django 2.1.2 on 2018-12-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0008_auto_20181214_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='award',
            field=models.ManyToManyField(blank=True, to='lottery.Award'),
        ),
    ]
