# Generated by Django 2.1.2 on 2018-12-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_auto_20181214_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='award_content',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='award',
            name='award_group_id',
            field=models.IntegerField(default=1),
        ),
    ]
