# Generated by Django 2.1.2 on 2018-12-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0010_auto_20181231_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='award_amount',
            field=models.IntegerField(default=1),
        ),
    ]
